import { useCallback, useEffect, useMemo, useState } from 'react'
import { api } from '../../services/api'
import { Badge } from '../ui/Badge'
import { Drawer } from '../ui/Drawer'
import { EventStream } from '../events/EventStream'
import { useEventStream } from '../../hooks/useEventStream'

const text=(v:any)=>v||'-'
const statusVariant=(s:string)=>s==='running'?'success':s==='completed'?'info':s==='failed'?'danger':s==='paused'?'warning':'default'
export function ObjectiveLeadsPage({id,onBack}:{id:string,onBack:()=>void}){
 const [objective,setObjective]=useState<any>();const [leads,setLeads]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selected,setSelected]=useState<any>();
 const [search,setSearch]=useState('');const [country,setCountry]=useState('');const [status,setStatus]=useState('');const [source,setSource]=useState('');const [minScore,setMinScore]=useState('');const [sort,setSort]=useState('created_at');const [direction,setDirection]=useState('desc');const [page,setPage]=useState(1);const [meta,setMeta]=useState({total:0,last_page:1});const [debugOpen,setDebugOpen]=useState(true)
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);setError('');try{const [o,r]=await Promise.all([api.objective(Number(id)),api.leads({objective_id:id,search,country,status,source,min_score:minScore,sort,direction,page:String(page),per_page:'25'})]);setObjective(o);setLeads(r.data||[]);setMeta({total:r.total||0,last_page:r.last_page||1})}catch(e:any){setError(e.message||'Could not load objective')}finally{setLoading(false)}},[id,search,country,status,source,minScore,sort,direction,page])
 const stream=useEventStream(e=>{if(['lead.created','api.response','agent.started','agent.completed','agent.paused','agent.resumed','agent.stopped'].includes(e.type))load(true)},id)
 useEffect(()=>{load()},[load])
 useEffect(()=>setPage(1),[search,country,status,source,minScore,sort,direction])
 const progress=objective?.progress||0;const countries=useMemo(()=>[...new Set(leads.map(l=>l.country_code).filter(Boolean))].sort() as string[],[leads]);const statuses=useMemo(()=>[...new Set(leads.map(l=>l.status).filter(Boolean))].sort() as string[],[leads]);const sources=useMemo(()=>[...new Set(leads.map(l=>l.source).filter(Boolean))].sort() as string[],[leads])
 if(loading&&!objective)return <div className="bg-white border rounded-2xl p-12 text-center text-zinc-400" role="status">Loading objective leads...</div>
 if(error&&!objective)return <div className="bg-white border border-red-200 rounded-2xl p-8 text-center"><h2 className="font-bold text-lg">Objective not found</h2><p className="text-sm text-zinc-500 mt-2">The objective may have been deleted or the link is invalid.</p><div className="mt-5 flex justify-center gap-2"><button onClick={onBack} className="border px-4 py-2 rounded-lg text-sm">Back to objectives</button><button onClick={()=>load()} className="bg-zinc-900 text-white px-4 py-2 rounded-lg text-sm">Try again</button></div></div>
 return <div className="space-y-5">
  <button onClick={onBack} className="text-sm text-zinc-500 hover:text-zinc-900">← Back to objectives</button>
  <section className="bg-white border rounded-2xl p-4 md:p-5">
   <div className="flex justify-between gap-3 flex-wrap"><div><div className="flex items-center gap-2 flex-wrap"><h1 className="text-xl font-bold">{objective.name}</h1><Badge variant={statusVariant(objective.status) as any}>{objective.status}</Badge><span className="text-xs text-zinc-400 font-mono">Objective #{id}</span></div><p className="text-sm text-zinc-500 mt-1">{objective.description}</p></div><button onClick={()=>load()} disabled={loading} className="border px-3 py-2 rounded-lg text-sm h-fit disabled:opacity-50">{loading?'Refreshing...':'Refresh data'}</button></div>
   <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-5"><div><div className="text-xs text-zinc-500">Leads found</div><div className="text-xl font-bold">{objective.leads_discovered||0}</div></div><div><div className="text-xs text-zinc-500">Qualified</div><div className="text-xl font-bold">{objective.qualified||0}</div></div><div><div className="text-xs text-zinc-500">Target</div><div className="text-xl font-bold">{objective.target_leads||'-'}</div></div><div><div className="text-xs text-zinc-500">Iterations</div><div className="text-xl font-bold">{objective.iteration_count||0}</div></div></div>
   {objective.target_leads&&<div className="mt-4"><div className="flex justify-between text-xs"><span>Progress</span><span>{progress}%</span></div><div className="h-2 bg-zinc-100 rounded-full mt-1 overflow-hidden"><div className="h-full bg-emerald-600" style={{width:`${progress}%`}}/></div></div>}
  </section>
  {error&&<div className="bg-red-50 border border-red-200 text-red-700 rounded-xl p-3 text-sm">{error}</div>}
  <section className="space-y-3">
   <div className="flex items-center justify-between"><h2 className="font-bold text-lg">Discovered leads</h2><a href={api.exportUrl({objective_id:id})} className="border bg-white px-3 py-2 rounded-lg text-sm">Export CSV</a></div>
   <div className="flex flex-wrap gap-2 bg-zinc-50 border rounded-xl p-2">
    <input aria-label="Search leads" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, company, website, location..." className="flex-1 min-w-[220px] border rounded-lg px-3 py-2 text-sm bg-white"/>
    <select aria-label="Filter country" value={country} onChange={e=>setCountry(e.target.value)} className="border rounded-lg px-2 py-2 text-sm bg-white"><option value="">All locations</option>{countries.map(x=><option key={x}>{x}</option>)}</select>
    <select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)} className="border rounded-lg px-2 py-2 text-sm bg-white"><option value="">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select>
    <select aria-label="Filter source" value={source} onChange={e=>setSource(e.target.value)} className="border rounded-lg px-2 py-2 text-sm bg-white"><option value="">All sources</option>{sources.map(x=><option key={x}>{x}</option>)}</select>
    <select aria-label="Minimum score" value={minScore} onChange={e=>setMinScore(e.target.value)} className="border rounded-lg px-2 py-2 text-sm bg-white"><option value="">Any score</option><option value="50">50+</option><option value="70">70+</option><option value="80">80+</option></select>
    <select aria-label="Sort leads" value={sort} onChange={e=>setSort(e.target.value)} className="border rounded-lg px-2 py-2 text-sm bg-white"><option value="created_at">Date found</option><option value="updated_at">Last updated</option><option value="name">Name</option><option value="company">Company</option><option value="score">Score</option><option value="status">Status</option><option value="source">Source</option></select>
    <button aria-label="Toggle sort direction" onClick={()=>setDirection(x=>x==='asc'?'desc':'asc')} className="border bg-white px-3 py-2 rounded-lg">{direction==='asc'?'↑':'↓'}</button>
   </div>
   <div className="bg-white border rounded-xl overflow-hidden"><div className="overflow-auto"><table className="w-full text-sm min-w-[980px]"><thead className="bg-zinc-50 border-b"><tr>{['Name','Company / website','Location','Score','Status','Source','Found / updated'].map(x=><th key={x} className="text-left p-3 font-semibold">{x}</th>)}</tr></thead><tbody>{leads.map(l=><tr key={l.id} onClick={()=>setSelected(l)} className="border-t hover:bg-zinc-50 cursor-pointer"><td className="p-3"><div className="font-medium">{text(l.full_name||`${l.first_name||''} ${l.last_name||''}`.trim())}</div><div className="text-xs text-zinc-500">{text(l.email)}</div></td><td className="p-3"><div>{text(l.company_name)}</div>{(l.website_url||l.company_domain)&&<a href={l.website_url||`https://${l.company_domain}`} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()} className="text-xs text-blue-600">{l.website_url||l.company_domain} ↗</a>}</td><td className="p-3">{text([l.city,l.country_name||l.country_code].filter(Boolean).join(', '))}</td><td className="p-3 font-semibold">{l.lead_score}</td><td className="p-3"><Badge>{text(l.status)}</Badge></td><td className="p-3">{text(l.source)}</td><td className="p-3 text-xs"><div>{l.created_at?new Date(l.created_at).toLocaleString():'-'}</div><div className="text-zinc-400">{l.updated_at?new Date(l.updated_at).toLocaleString():'-'}</div></td></tr>)}</tbody></table></div>
    {!loading&&!leads.length&&<div className="p-12 text-center"><div className="font-medium">No leads found for this objective</div><p className="text-sm text-zinc-500 mt-1">{search||country||status||source||minScore?'Clear or change the filters.':'Start the objective or wait for lead discovery.'}</p></div>}
    <div className="flex justify-between items-center p-3 border-t bg-zinc-50 text-xs"><span>{meta.total} lead{meta.total===1?'':'s'}</span><div className="flex gap-2 items-center"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="border bg-white px-2 py-1 rounded disabled:opacity-40">Previous</button><span>Page {page} of {meta.last_page}</span><button disabled={page>=meta.last_page} onClick={()=>setPage(p=>p+1)} className="border bg-white px-2 py-1 rounded disabled:opacity-40">Next</button></div></div>
   </div>
  </section>
  <section><button aria-expanded={debugOpen} onClick={()=>setDebugOpen(x=>!x)} className="w-full flex justify-between items-center bg-white border rounded-xl p-3 font-semibold text-sm"><span>Objective event debugger</span><span>{debugOpen?'Hide':'Show'} · {stream.events.length} events</span></button>{debugOpen&&<div className="mt-2"><EventStream {...stream} compact/></div>}</section>
  <Drawer open={!!selected} onClose={()=>setSelected(undefined)} title="Lead details">{selected&&<div className="space-y-4"><div><h3 className="text-lg font-bold">{text(selected.full_name||`${selected.first_name||''} ${selected.last_name||''}`.trim())}</h3><p className="text-sm text-zinc-500">{text(selected.position_title)} · {text(selected.company_name)}</p></div><dl className="grid grid-cols-2 gap-3 text-sm">{Object.entries({Email:selected.email,Phone:selected.phone,Website:selected.website_url||selected.company_domain,Location:[selected.city,selected.country_name||selected.country_code].filter(Boolean).join(', '),Industry:selected.industry_name,Department:selected.department,Score:selected.lead_score,Status:selected.status,Source:selected.source,Created:selected.created_at,Updated:selected.updated_at}).map(([k,v])=><div key={k}><dt className="text-zinc-500">{k}</dt><dd className="break-all">{text(v)}</dd></div>)}</dl><details className="border rounded-xl p-3"><summary className="font-semibold cursor-pointer">Complete lead payload</summary><button onClick={()=>navigator.clipboard.writeText(JSON.stringify(selected,null,2))} className="border px-2 py-1 rounded text-xs mt-3">Copy payload</button><pre className="text-xs bg-zinc-950 text-zinc-200 p-3 rounded-lg overflow-auto mt-2 whitespace-pre-wrap break-all">{JSON.stringify({...selected,raw_data:(()=>{try{return JSON.parse(selected.raw_data)}catch{return selected.raw_data}})()},null,2)}</pre></details></div>}</Drawer>
 </div>
}
